import Login from "./login";
import Register from "./register";
import Forgot from "./forgot";
import Home from "./home";
import Verification from "./verification";
import Dashboard from "./userpanel/dashboard";
import Swap from "./userpanel/swap";
import Wallet from "./userpanel/wallet";
import History from "./userpanel/history";
import Kyc from "./userpanel/kyc";
import Welcome_DashB from "./userpanel/welcome";
import Market from "./market";
import Security from "./userpanel/Security";
import Payment from "./userpanel/Payment";
import Setting from "./userpanel/Setting";
export {Login,Register,Forgot,Verification,Kyc,Home,Welcome_DashB,Dashboard,Swap,Wallet,History,Security,Payment,Setting,Market};
